declare -x Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.fYQFwJXOER/Render
declare -x COLORTERM=truecolor
declare -x COMMAND_MODE=unix2003
declare -x GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
declare -x HOME=/Users/ajari
declare -x LANG=en_US.UTF-8
declare -x LESS=-R
declare -x LOGNAME=ajari
declare -x LSCOLORS=Gxfxcxdxbxegedabagacad
declare -x MallocNanoZone=0
declare -x OLDPWD
declare -x ORIGINAL_XDG_CURRENT_DESKTOP=undefined
declare -x PAGER=less
declare -x PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/ajari/Library/Python/3.9/bin:/Library/Python/3.7/lib/python/site-packages:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/ajari/Library/Python/3.9/bin:/Library/Python/3.7/lib/python/site-packages
declare -x PS1=\\[\\033[38;5;2m\\]*_*\\[(B[m\\]\\[\\033[38;5;11m\\]@\\[(B[m\\]\\u\\[(B[m\\]\\[\\033[38;5;75m\\]\\t\\[(B[m\\]\\[\\033[38;5;1m\\]-\\[(B[m\\]\\[\\033[38;5;118m\\]-\\[(B[m\\]\\[\\033[38;5;196m\\]>\\[(B[m\\]\\[\\033[38;5;2m\\]\\w\\[(B[m\\]
declare -x PWD=/Users/ajari/Desktop/minishell
declare -x SECURITYSESSIONID=186a8
declare -x SHELL=/bin/zsh
declare -x SHLVL=2
declare -x SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.hmZGuM62ty/Listeners
declare -x TERM=xterm-256color
declare -x TERM_PROGRAM=vscode
declare -x TERM_PROGRAM_VERSION=1.75.1
declare -x TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000lqm0004xx/T/
declare -x USER=ajari
declare -x USER_ZDOTDIR=/Users/ajari
declare -x VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
declare -x VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
declare -x VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
declare -x VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n0000lqm0004xx/T/vscode-git-6434010bcd.sock
declare -x VSCODE_INJECTION=1
declare -x XPC_FLAGS=0x0
declare -x XPC_SERVICE_NAME=0
declare -x ZDOTDIR=/Users/ajari
declare -x ZSH=/Users/ajari/.oh-my-zsh
declare -x __CF_USER_TEXT_ENCODING=0x13BD:0x0:0x0
\n
TERM_PROGRAM=vscode
TERM=xterm-256color
SHELL=/bin/zsh
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000lqm0004xx/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.fYQFwJXOER/Render
TERM_PROGRAM_VERSION=1.75.1
ZDOTDIR=/Users/ajari
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MallocNanoZone=0
ZSH=/Users/ajari/.oh-my-zsh
USER=ajari
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.hmZGuM62ty/Listeners
__CF_USER_TEXT_ENCODING=0x13BD:0x0:0x0
PAGER=less
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/ajari/Library/Python/3.9/bin:/Library/Python/3.7/lib/python/site-packages:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/ajari/Library/Python/3.9/bin:/Library/Python/3.7/lib/python/site-packages
USER_ZDOTDIR=/Users/ajari
PWD=/Users/ajari/Desktop/minishell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
PS1=\[\033[38;5;2m\]*_*\[(B[m\]\[\033[38;5;11m\]@\[(B[m\]\u\[(B[m\]\[\033[38;5;75m\]\t\[(B[m\]\[\033[38;5;1m\]-\[(B[m\]\[\033[38;5;118m\]-\[(B[m\]\[\033[38;5;196m\]>\[(B[m\]\[\033[38;5;2m\]\w\[(B[m\]
XPC_SERVICE_NAME=0
VSCODE_INJECTION=1
SHLVL=2
HOME=/Users/ajari
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LESS=-R
LOGNAME=ajari
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n0000lqm0004xx/T/vscode-git-6434010bcd.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
SECURITYSESSIONID=186a8
COLORTERM=truecolor
_=/usr/bin/env
